- Cargo.lock
- teerex/src/benchmarking.rs
- teerex/src/lib.rs
- teerex/src/tests/tests.rs
- teerex/src/weights.rs
Related to issue https://github.com/integritee-network/worker/issues/457
Removes `CallConfirmation,` and splits `BlockConfirmation` in `SidechainblockProposed` and `ParentchainblockProcessed`
TODO:
> Change Call- and BlockConfirmation to SidechainblockProposed and ParentchainblockProcessed

- teerex/src/benchmarking.rs
- teerex/src/lib.rs
- teerex/src/tests/tests.rs
- teerex/src/weights.rs
as discussed in PR https://github.com/integritee-network/worker/pull/487#discussion_r744827609
> rename to chainblock to chain_block

- teeracle/Cargo.toml
- teeracle/src/benchmarking.rs
- teeracle/src/lib.rs
- teeracle/src/mock.rs
- teeracle/src/tests.rs
- teeracle/src/weights.rs
Update of exchange rate can only be done by a trusted oracle
> Add whitelist of trusted exchange rate oracles 

- Cargo.lock
- claims/src/lib.rs
- parentchain/Cargo.toml
- parentchain/src/mock.rs
- primitives/teerex/Cargo.toml
- teeracle/Cargo.toml
- teeracle/src/mock.rs
- teerex/Cargo.toml
- teerex/ias-verify/Cargo.toml
- teerex/src/mock.rs
Update Substrate updated sp-core to 4.1.0-dev like in:
https://github.com/paritytech/substrate/blob/b9cafba3d0e7a5950ac78d81e4ab7f2074938666/primitives/core/Cargo.toml
> Update sp-core to substrate master version 4.1.0-dev

- primitives/sidechain/Cargo.toml
- primitives/sidechain/src/traits/mod.rs
- primitives/sidechain/src/types/header.rs
So we do not have to import the massive crypto primitives into the parachain runtime
> [sidechain-primitives] make no_std compatible + add full-crypto feature flag

- parentchain/Cargo.toml
- parentchain/test/Cargo.toml
- primitives/claims/Cargo.toml
- primitives/common/Cargo.toml
- primitives/sidechain/Cargo.toml
- primitives/teeracle/Cargo.toml
- primitives/teerex/Cargo.toml
- primitives/types/Cargo.toml
- primitives/utils/Cargo.toml
- sidechain/Cargo.toml
- sidechain/sidechain-block-verification/Cargo.toml
- sidechain/test/Cargo.toml
- teeracle/Cargo.toml
- teerex/Cargo.toml
- teerex/ias-verify/Cargo.toml
- test-utils/Cargo.toml
- Switch to edition 2021
- Standardize the fields license, authors, homepage, repository
- I would update the remaining repos in a similar way. 
- Note that there is the pallet-claims in this repo from parity which I did not change
> Update Cargo.toml files

- .github/workflows/ci.yml
- sidechain/src/benchmarking.rs
- sidechain/src/lib.rs
- sidechain/src/mock.rs
- sidechain/src/tests.rs
- teeracle/src/benchmarking.rs
belongs to [#1003](https://github.com/integritee-network/worker/issues/1003)
> Propose every nth block as finality candidate instead of all the blocks

- .github/workflows/ci.yml
- sidechain/src/benchmarking.rs
- sidechain/src/lib.rs
- sidechain/src/mock.rs
- sidechain/src/tests.rs
- teeracle/src/benchmarking.rs
This PR aims to get rid of the current `develop` branch, which was a temporary stand-in as the polkadot update (0.9.29) was blocked for a while in `worker`.
> Merge `develop` branch with updated polkadot

- Cargo.lock
- about.toml
- claims/Cargo.toml
- claims/src/lib.rs
- parentchain/Cargo.toml
- parentchain/src/lib.rs
- primitives/claims/Cargo.toml
- primitives/common/Cargo.toml
- primitives/sidechain/Cargo.toml
- primitives/teeracle/Cargo.toml
- primitives/teerex/Cargo.toml
- sidechain/Cargo.toml
- sidechain/src/lib.rs
- teeracle/Cargo.toml
- teeracle/src/lib.rs
- teerex/Cargo.toml
- teerex/ias-verify/Cargo.toml
- teerex/src/lib.rs
upgrade to polkadot-v0.9.36
- Only bump up to version v0.9.36
- pallet-paratchain onchain method add call_index, pallet-claims & pallet-teerex & pallet-teeracle & pallet-siedchain declared as dev_mode   Related substrate PR  https://github.com/paritytech/substrate/pull/11381
- pallet-claims toml file add `license = "Apache-2.0"`
> upgrade to Polkadot v0.9.36

- Cargo.lock
- primitives/xcm-transactor/src/lib.rs
- xcm-transactor/Cargo.toml
- xcm-transactor/src/lib.rs
My lesson to learn that the CI for the `pallets` repository does not catch issues when importing said pallet into a the parachain runtime. This fixes the issue of importing the xcm-transactor pallet.
> Updates to xcm-transactor-pallet to allow parachain to import successfully

- xcm-transactor/src/lib.rs
- xcm-transactor/src/mock.rs
- Need to add custom origin for governance vote to suffice for making the `send_swap_ump()` call
> Adding custom origin for xcm-transactor pallet

- primitives/xcm-transactor/src/lib.rs
- xcm-transactor/src/mock.rs
- `construct_transact_xcm()` in xcm-transactor-primitives was incorrect
- Adding `paraId` generic param to `RelayCallBuilder` in xcm-transactor-primitives to support Refunding assets which would otherwise be trapped in the holding register
- Including pallet-xcm-transactor in the shellruntime
> Fix XCM Transact to be correct and add transactor to shell runtime

- primitives/xcm-transactor/src/lib.rs
- xcm-transactor/src/lib.rs
- xcm-transactor/src/mock.rs
- xcm-transactor/src/tests.rs
We had the issue that our xcm transact failed on the real Kusama chain because the xcm weights are different from the rococo-local setup. Hence, we should expose teh xcm values as args, so we don't run into the issue again that the call fails and there is nothing we can do without a runtime upgrade.
Tested that it works on a rococo local setup
> [xcm-transactor] expose xcm args in swap call

- teerex/src/lib.rs
- teerex/src/tests/test_cases.rs
Currently there is an underflow if the timestamp is 0. I'm not quite sure how the timestamp-pallets works, but I think we should at least detect it.
> Detect an underflow if the timestamp is zero

- teerex/sgx-verify/src/lib.rs
`std` is not available, `core` should be used.
> use core:: instead of std:: for mem::size_of

- teerex/sgx-verify/src/lib.rs
This function is used in the worker for extracting `FMSPC` from a raw DCAP quote.
> sgx-verify: add function extract_tcb_info_from_raw_dcap_quote

- Cargo.lock
- claims/Cargo.toml
- parentchain/Cargo.toml
- primitives/claims/Cargo.toml
- primitives/common/Cargo.toml
- primitives/sidechain/Cargo.toml
- primitives/teeracle/Cargo.toml
- primitives/teerex/Cargo.toml
- primitives/xcm-transactor/Cargo.toml
- primitives/xcm-transactor/src/lib.rs
- sidechain/Cargo.toml
- teeracle/Cargo.toml
- teerex/Cargo.toml
- teerex/sgx-verify/Cargo.toml
- xcm-transactor/Cargo.toml
- xcm-transactor/src/lib.rs
- xcm-transactor/src/mock.rs
- xcm-transactor/src/tests.rs
Based on @BillyWooo's  work in #125, but fixing the xcm stuff.
Notable commit: https://github.com/integritee-network/pallets/pull/159/commits/78a0f30adb81b1e09927c9c2714f8527fe79742a the linker can't handle a wasmtime version mismatch between subxt (used in tests) and substrate, there is a duplicate function def error then. Luckily, we can disable the wasm stuff in subxt.
> polkadot v0.9.38

- primitives/teerex/src/lib.rs
- teerex/sgx-verify/src/lib.rs
The original issue was titled _Verify attributes and miscselectMask of the quoting enclave _, but the miscselect verification was already there, so I just added the attributes part.
Fixes #127
> Verify attributes of the quoting enclave 

- sidechain/src/tests.rs
- teeracle/src/benchmarking.rs
- teeracle/src/tests.rs
- teerex/src/benchmarking.rs
- teerex/src/lib.rs
- teerex/src/tests/skip_ias_check_tests.rs
- teerex/src/tests/test_cases.rs
- teerex/src/weights.rs
> DCAP: rename `register_enclave` to `register_ias_enclave`

- LICENSE
- teerex/LICENSE
- teerex/README.md
- teerex/sgx-verify/src/collateral.rs
- teerex/sgx-verify/src/ephemeral_key.rs
- teerex/sgx-verify/src/lib.rs
- teerex/sgx-verify/src/netscape_comment.rs
- teerex/sgx-verify/src/tests.rs
- teerex/sgx-verify/src/utils.rs
- teerex/src/benchmarking.rs
- teerex/src/lib.rs
- teerex/src/mock.rs
- teerex/src/weights.rs
if this license actually prohibits forking our repo, we should extract teerex into its own repo. not sure TBH. but we can just go with this and change it if someone complains that forking is hereby prohibited
The basic goal is to be transparent, but protect integritee network from copycats on its basic value proposition (or DIY RA on other parachains)
> change license for teerex to MS-RSL

- .github/workflows/ci.yml
As seen in the [GitHub Actions run logs ](https://github.com/integritee-network/pallets/actions/runs/4972841445?pr=167) these two actions needed to be bumped.
> gha: bump actions to remove Nodejs12 deprecation warnings

- Cargo.lock
- claims/Cargo.toml
- claims/src/lib.rs
- parentchain/Cargo.toml
- parentchain/src/lib.rs
- parentchain/src/mock.rs
- parentchain/src/weights.rs
- primitives/claims/Cargo.toml
- primitives/common/Cargo.toml
- primitives/sidechain/Cargo.toml
- primitives/teeracle/Cargo.toml
- primitives/teerex/Cargo.toml
- primitives/xcm-transactor/Cargo.toml
- sidechain/Cargo.toml
- sidechain/src/lib.rs
- sidechain/src/mock.rs
- sidechain/src/weights.rs
- teeracle/Cargo.toml
- teeracle/src/lib.rs
- teeracle/src/mock.rs
- teeracle/src/weights.rs
- teerex/Cargo.toml
- teerex/sgx-verify/Cargo.toml
- teerex/src/lib.rs
- teerex/src/mock.rs
- teerex/src/test_helpers.rs
- teerex/src/weights.rs
- xcm-transactor/Cargo.toml
- xcm-transactor/src/lib.rs
- xcm-transactor/src/mock.rs
See the following substrate PRs for details:
- https://github.com/paritytech/substrate/pull/13535
- https://github.com/paritytech/substrate/pull/13475
- https://github.com/paritytech/substrate/pull/13798
For the last one I opted for suppressing the warning, but will open an issue for benchmarking it.
Closes https://github.com/integritee-network/pallets/issues/172
> Polkadot update v0.9.42

- parentchain/src/lib.rs
- parentchain/src/mock.rs
- parentchain/src/tests.rs
- primitives/teerex/src/lib.rs
- teerex/src/lib.rs
- teerex/src/tests/test_cases.rs
closes #174
closes #179 
Some dispatchables are missing events..
> Add events for all dispatchables

- .github/workflows/ci.yml
- Cargo.lock
- primitives/teerex/Cargo.toml
- primitives/teerex/src/lib.rs
- sidechain/src/benchmarking.rs
- sidechain/src/lib.rs
- sidechain/src/mock.rs
- sidechain/src/tests.rs
- teeracle/Cargo.toml
- teeracle/src/benchmarking.rs
- teeracle/src/lib.rs
- teeracle/src/mock.rs
- teeracle/src/tests.rs
- teerex/Cargo.toml
- teerex/src/benchmarking.rs
- teerex/src/lib.rs
- teerex/src/mock.rs
- teerex/src/tests/test_cases.rs
closes #186 #183 #152 
breaking changes:
* ShardStatus will replace WorkerForShard logic
* remove skip-ias
* introduce MultiEnclave
non-breaking changes:
* no automatic garbage collection OnTimestamp anymore. lazy dispatchable introduced
> teerex refactor 2

- xcm-transactor/src/lib.rs
* Closes #210 
Contains the commits that were deployed on the rococo runtime (https://github.com/integritee-network/parachain/pull/229) for debugging the slot swap UMP from https://github.com/integritee-network/pallets/tree/cl/more-expressive-xcm-error, but rebased on master
> [xcm-transactor] more expressive XCM error handling

- Cargo.lock
- teerex/sgx-verify/src/lib.rs
- teerex/sgx-verify/src/tests.rs
- teerex/src/lib.rs
- teerex/src/tests/test_cases.rs
neither substrate_api_client nor js/apps properly enrich nested errors (although we derive PalletError and TypeInfo), but at least we propagate an error code which we can be matched to the enum manually
So, a signature error on sgx_verify now looks like this:
`[2023-09-12T14:54:00Z ERROR integritee_cli::base_cli::commands::register_tcb_info] register_tcb_info extrinsic failed Dispatch(Module(ModuleError { pallet: "Teerex", error: "SgxVerifyError", description: ["An error originating in the sgx_verify crate"], error_data: ModuleErrorData { pallet_index: 50, error: [15, 34, 0, 0] } })) `
or:
34 (or 2nd byte in raw error `0x22`) is the index of the `sgx_verify::Error::RsaSignatureInvalid`
> Explicit errors for sgx_verify

- teerex/src/lib.rs
- teerex/src/migrations.rs
tested against rococo and kusama:
```
./target/release/integritee-collator try-runtime   --chain integritee-rococo   --runtime ./target/release/wbuild/integritee-runtime/integritee_runtime.wasm   on-runtime-upgrade --checks=all   live --uri wss://rococo.api.integritee.network:443
2023-09-15 13:54:01 replacing wss:// in uri with https://: "https://rococo.api.integritee.network:443" (ws is currently unstable for fetching remote storage, for more see https://github.com/paritytech/jsonrpsee/issues/1086)    
2023-09-15 13:54:01 since no at is provided, setting it to latest finalized head, 0xb495449e0d711cc5f03524f956b6c81c3fdb57936894899715f81c5584d156fd    
2023-09-15 13:54:01 since no prefix is filtered, the data for all pallets will be downloaded    
2023-09-15 13:54:01 scraping key-pairs …
```
> add storage migration teerex V1->V2

- Cargo.lock
- primitives/sidechain/src/lib.rs
- sidechain/src/lib.rs
- sidechain/src/tests.rs
closes #235 
the previous logic where validateers had to announce their next block to be expected was too brittle and had no effective security benefit. All we need is:
* only authorized enclaves may finalize
* block numbers must increase monotonically
* avoid forks
avoiding forks is still the naive solution: just finalize blocks from the first validateer appearing in the ShardStatus, which usually is the primary validateer who created the shard
> accept any new sidechain block from authorized enclave for shard

- Cargo.lock
- parentchain/src/lib.rs
- parentchain/src/mock.rs
- parentchain/src/tests.rs
- parentchain/src/weights.rs
we need block timestamps especially for shard creation sync across parentchains to enable fast-sync
....and fix weight info on the side
> parentchain set_now for block timestamps

- Cargo.lock
- Cargo.toml
- claims/Cargo.toml
- enclave-bridge/Cargo.toml
- sidechain/Cargo.toml
- teeracle/Cargo.toml
- teerex/Cargo.toml
- xcm-transactor/Cargo.toml
we had a std leak in test-utils dependency when enabling runtime-benchmarks
along the way of debugging, I streamlined more feature propagation similar to parachain template
> fixing collator node build benchmark feature propagation

- sidechain/src/benchmarking.rs
- sidechain/src/lib.rs
- sidechain/src/tests.rs
closes #242 
must bump tx version
> implement SBliFF

- .cargo/zepter.yaml
- .github/workflows/ci.yml
- Cargo.lock
- asset-registry/Cargo.toml
- claims/Cargo.toml
- enclave-bridge/Cargo.toml
- parentchain/Cargo.toml
- primitives/enclave-bridge/Cargo.toml
- primitives/xcm-transactor/Cargo.toml
- sidechain/Cargo.toml
- teeracle/Cargo.toml
- teerex/Cargo.toml
- xcm-transactor/Cargo.toml
This was needed anyhow to fix the build with the `runtime-benchmark` feature in the polkadot-v1.12.0 branch
> Add zepter config and add it to the CI

- Cargo.lock
- Cargo.toml
- enclave-bridge/src/benchmarking.rs
- primitives/teerdays/src/lib.rs
- teeracle/Cargo.toml
- teeracle/src/benchmarking.rs
- teeracle/src/mock.rs
- teeracle/src/tests.rs
- teeracle/src/weights.rs
- teerdays/src/lib.rs
- teerdays/src/weights.rs
- teerex/Cargo.toml
- teerex/sgx-verify/src/collateral.rs
- teerex/src/benchmarking.rs
- teerex/src/mock.rs
- teerex/src/tests/test_cases.rs
our benchmarks failed with mismatch in slot to timestamp.
this fixes it
> fixing benchmarks

- primitives/xcm-transactor/src/lib.rs
- teerdays/src/lib.rs
- teerdays/src/tests.rs
> [teerdays] explicitly add burned teerdays to event

- teerdays/src/lib.rs
we can't allow bond_extra during unlocking period - or we need to change the math to calculate the new lock value. Otherwise, the lock will be too low after bond_extra
(UI already disables this)
> fix premature unlock with bond_extra

- .github/workflows/ci.yml
v3 is deprecated and will be removed on the 30.01.2025.
> [CI] bump artifact actions to v4

- .github/workflows/ci.yml
- scripts/run_for_all_no_std_crates.sh
This PR fixes and improves the wasm CI. The script was broken such that it only reported an error if the last crate build failed. After this change, it will:
* compile all crates and list an overview of the failed cargo checks at the end. 
* Use GA grouping to have foldable sections for each crate for a better log structure
Closes #284
> Correctly report error in wasm build CI

- porteer/src/benchmarking.rs
- porteer/src/lib.rs
- porteer/src/mock.rs
- porteer/src/tests.rs
closes #291 
The porteer pallet maintains a monotonic counter and passes the incremented nonce along to the implementation of `PortTokens` trait. The idea is that this implementation will include the nonce in the payload sent to the cousin's `mint_ported_tokens` 
This way, each call to `port_tokens` will result in unique and traceable messages
> introduce porteer nonce
