integritee-network/pallets

Cargo.lock
claims/src/lib.rs
teeracle/Cargo.toml
teerex/Cargo.toml
teerex/ias-verify/Cargo.toml
teerex/ias-verify/src/lib.rs
teerex/src/lib.rs
teerex/src/mock.rs

Upgrade substrate to master#e40710abffde7dffcd30eb51756a7a1e9eb0e249

Upgrade substrate dep to > v14 metadata

---

Cargo.lock
claims/src/lib.rs
primitives/teerex/Cargo.toml
primitives/teerex/src/lib.rs
rust-toolchain.toml
teeracle/Cargo.toml
teeracle/src/lib.rs
teeracle/src/weights.rs
teerex/Cargo.toml
teerex/ias-verify/Cargo.toml
teerex/src/lib.rs
tests-utils/Cargo.toml

update rust tool chain
clean std features: cargo build --release --no-default-feature runs

Upgrade to substrate 7406442bea0194ffcafc4e8d48d895d4d8d11346

---

Cargo.lock
Cargo.toml
parentchain/Cargo.toml
parentchain/src/lib.rs
parentchain/src/mock.rs
parentchain/src/tests.rs
parentchain/src/weights.rs

to get parentchain pallet.
Update pallet to new substrate

Add parentchain-pallet

---

Cargo.lock
Cargo.toml
primitives/common/Cargo.toml
primitives/common/src/lib.rs
primitives/teeracle/Cargo.toml
primitives/teeracle/src/lib.rs
teeracle/src/benchmarking.rs
teeracle/src/lib.rs
teeracle/src/tests.rs

Whitelist is a storage map. Key: source, Value: WeakBoundedVec of mrenclaves . A mrenclave in the list can operate the source.
ExchangeRates is a storage double map: Key1: the trading pair, Key2: the source, Value the exchange rate.

Teeracle support multiple sources and multiple trading pairs

---

claims/Cargo.toml
parentchain/Cargo.toml
primitives/claims/Cargo.toml
primitives/teeracle/Cargo.toml
primitives/teerex/Cargo.toml
teeracle/Cargo.toml
teerex/Cargo.toml
teerex/ias-verify/Cargo.toml
tests-utils/Cargo.toml

This also removes the resolver warnings.

cargo 2021 edition

---

claims/Cargo.toml

Update sp-core to substrate master version 4.1.0-dev 

---

teeracle/src/lib.rs
teeracle/src/mock.rs
teerex/src/benchmarking.rs
teerex/src/lib.rs
teerex/src/mock.rs
teerex/src/tests/tests.rs

Metadata of pallet did not change at all.

Update pallet teerex to frame v2

---

claims/Cargo.toml
parentchain/Cargo.toml
primitives/claims/Cargo.toml
primitives/common/Cargo.toml
primitives/teeracle/Cargo.toml
primitives/teerex/Cargo.toml
teeracle/Cargo.toml
teerex/Cargo.toml
teerex/ias-verify/Cargo.toml

- substrate branch set to polkadot-v0.9.19

Bump to polkadot 0.9.19

---

claims/Cargo.toml
parentchain/Cargo.toml
primitives/claims/Cargo.toml
primitives/common/Cargo.toml
primitives/teeracle/Cargo.toml
primitives/teerex/Cargo.toml
teeracle/Cargo.toml
teerex/Cargo.toml
teerex/ias-verify/Cargo.toml

update to polkadot-v0.9.20

---

primitives/teerex/Cargo.toml
primitives/teerex/src/lib.rs
teeracle/src/mock.rs
teerex/src/benchmarking.rs
teerex/src/lib.rs
teerex/src/mock.rs
teerex/src/tests/tests.rs

* check that block number is consecutive to the previous one
* check that block hash equals the hash of the previous block
related to issue https://github.com/integritee-network/integritee-node/issues/115

Sidechain block finalization

---

claims/Cargo.toml
parentchain/Cargo.toml
primitives/claims/Cargo.toml
primitives/common/Cargo.toml
primitives/sidechain/Cargo.toml
primitives/teeracle/Cargo.toml
primitives/teerex/Cargo.toml
sidechain/Cargo.toml
teeracle/Cargo.toml
teerex/Cargo.toml
teerex/ias-verify/Cargo.toml

Polkadot v0.9.24

---

Cargo.lock
primitives/types/Cargo.toml
primitives/types/src/lib.rs

* Closes #72.
* https://github.com/integritee-network/worker/pull/892 the worker re-introduces them here.

[types] remove api-client definitions and dependency

---

teerex/src/lib.rs

Extremely proud of this achievement 😄

Remove outdated todo comment

---

sidechain/src/weights.rs

remove weights of  confirm_proposed_sidechain_block since call was removed in #84

remove weights of deprecated call

---

teerex/src/benchmarking.rs
teerex/src/lib.rs
teerex/src/tests/tests.rs

[Belongs to 838](https://github.com/integritee-network/worker/issues/838)

Add block number to ProcessedParentchainBlock event

---

.github/workflows/ci.yml
.taplo.toml
claims/Cargo.toml
primitives/sidechain/Cargo.toml
primitives/teeracle/Cargo.toml
primitives/teerex/Cargo.toml
teeracle/Cargo.toml
teerex/Cargo.toml
teerex/ias-verify/Cargo.toml
test-utils/Cargo.toml

- best config to match coding guidelines
- according to https://github.com/integritee-network/worker/issues/957
- enforces formatting of Cargo.toml in the CI

Add cargo.toml formatting with taplo

---

claims/src/lib.rs
rust-toolchain.toml
teerex/ias-verify/src/lib.rs
teerex/src/lib.rs

- Was causing issue in license check CI job
- Updated tool chain
- fixed Clippy complaints

Updating Rust tool chain to latest 10-22

---

claims/src/lib.rs
parentchain/src/lib.rs
sidechain/src/lib.rs
teeracle/src/lib.rs
teerex/src/lib.rs

Assign explicit indexes to pallet calls

---

about.toml
xcm-transactor/Cargo.toml
xcm-transactor/src/lib.rs
xcm-transactor/src/mock.rs
xcm-transactor/src/tests.rs

Not 100% sure if this is correct, but I think this is the best effort for now.

[xcm-transactor] add GPL-3 licence

---

Cargo.lock
claims/Cargo.toml
parentchain/Cargo.toml
primitives/claims/Cargo.toml
primitives/common/Cargo.toml
primitives/sidechain/Cargo.toml
primitives/teeracle/Cargo.toml
primitives/teerex/Cargo.toml
primitives/xcm-transactor/Cargo.toml
sidechain/Cargo.toml
teeracle/Cargo.toml
teerex/Cargo.toml
teerex/sgx-verify/Cargo.toml
xcm-transactor/Cargo.toml

as title, update to polkadot-v0.9.37

update to polkadot-v0.9.37

---

Cargo.lock
claims/Cargo.toml
parentchain/Cargo.toml
primitives/claims/Cargo.toml
primitives/common/Cargo.toml
primitives/sidechain/Cargo.toml
primitives/teeracle/Cargo.toml
primitives/teerex/Cargo.toml
primitives/xcm-transactor/Cargo.toml
sidechain/Cargo.toml
teeracle/Cargo.toml
teerex/Cargo.toml
teerex/sgx-verify/Cargo.toml
teerex/src/tests/test_cases.rs
xcm-transactor/Cargo.toml

as title. 
only update toml files.

update to polkadot-v0.9.39

---

Cargo.lock
primitives/teerex/src/lib.rs
sidechain/src/benchmarking.rs
teerex/sgx-verify/src/collateral.rs
teerex/sgx-verify/src/lib.rs
teerex/sgx-verify/src/test_data.rs
teerex/sgx-verify/src/tests.rs
teerex/src/benchmarking.rs
teerex/src/lib.rs
teerex/src/test_helpers.rs
teerex/src/tests/skip_ias_check_tests.rs
teerex/src/tests/test_cases.rs
test-utils/src/lib.rs

closes #185 
* we still assume no proxy attestation (like attesteer)
* adding fields to enclave struct
* renaming to specificly mention SGX wherever it is sgx-specific

teerex refactor 1

---

LICENSE
README.md
sidechain/LICENSE

along the logic of #168, protect the raison d'etre of the integritee network

change license for sidechain pallet to MS-RSL

---

sidechain/Cargo.toml
sidechain/src/benchmarking.rs
sidechain/src/lib.rs
sidechain/src/mock.rs
sidechain/src/tests.rs
sidechain/src/weights.rs
teerex/Cargo.toml

just aligning file headers, cargo.toml and LICENSE files

license cleanup

---

Cargo.lock
enclave-bridge/src/benchmarking.rs
enclave-bridge/src/lib.rs
enclave-bridge/src/mock.rs
enclave-bridge/src/tests/mod.rs
enclave-bridge/src/tests/test_indirect_invocation.rs
enclave-bridge/src/tests/test_publish_hash.rs
enclave-bridge/src/tests/test_shard_config.rs
enclave-bridge/src/weights.rs
primitives/common/src/lib.rs
primitives/enclave-bridge/src/lib.rs
sidechain/src/benchmarking.rs
sidechain/src/lib.rs
sidechain/src/tests.rs
teerex/src/lib.rs
teerex/src/weights.rs

closes #184 
* introduce updatable ShardConfig
* unit tests for sharded parentchain block confirmations with updated fingerprint
* unit tests for sharded sidechain block confirmations with updated fingerprint

introduce ShardConfig for enclave upgradability

---

enclave-bridge/src/benchmarking.rs
enclave-bridge/src/weights.rs

benchmark shield unshield

---

Cargo.lock
enclave-bridge/src/lib.rs
enclave-bridge/src/tests/test_indirect_invocation.rs
enclave-bridge/src/tests/test_publish_hash.rs
parentchain/src/lib.rs
sidechain/src/lib.rs
sidechain/src/tests.rs
teeracle/src/lib.rs
teeracle/src/tests.rs
teerex/src/lib.rs

closes #205 
* strictly use structs with named fields in Events
* strictly add docstrings to Events and Errors

Clean up Events and Errors and add docstrings

---

Cargo.lock
primitives/teerex/src/lib.rs
teerex/Cargo.toml
teerex/src/lib.rs
teerex/src/test_helpers.rs
teerex/src/tests/test_cases.rs

more helpful error handling and logging if TCB info check fails

---

teerex/src/lib.rs
teerex/src/migrations.rs

state migrations to teerex v1

---

Cargo.lock
parentchain/Cargo.toml
parentchain/src/lib.rs
parentchain/src/mock.rs
parentchain/src/tests.rs
parentchain/src/weights.rs

to abandon hardcoded keys in worker STF, we introduce this storage which is mainly used for fast-sync of parentchains to know when the relevant blocks start

[parentchain] shard creation storage

---

Cargo.lock
Cargo.toml
claims/src/lib.rs
enclave-bridge/Cargo.toml
enclave-bridge/src/mock.rs
enclave-bridge/src/tests/test_indirect_invocation.rs
parentchain/src/mock.rs
primitives/xcm-transactor/Cargo.toml
primitives/xcm-transactor/src/lib.rs
sidechain/Cargo.toml
sidechain/src/mock.rs
teeracle/Cargo.toml
teeracle/src/mock.rs
teerex/Cargo.toml
teerex/src/mock.rs
xcm-transactor/Cargo.toml
xcm-transactor/src/lib.rs
xcm-transactor/src/mock.rs

and depend on crates.io
that was lightweight :-)

upgrade to polkadot v1.3.0

---

Cargo.lock
Cargo.toml

closes #250 
literally a 5min task :1st_place_medal:

upgrade to polkadot-v1.5.0 dependencies

---

Cargo.lock
Cargo.toml

Yet another update PR ;) Builds on the other PRs.
It also adds a zepter configuration and a zepter CI test. I did this because the missing feature propagation broke our build. :)

polkadot v1.12.0

---

teerdays/src/benchmarking.rs

the benchmark test amounts were too small for our parachain config

fix benchmarks for higher ED

---

Cargo.lock
Cargo.toml
porteer/Cargo.toml
porteer/src/benchmarking.rs
porteer/src/lib.rs
porteer/src/mock.rs
porteer/src/tests.rs
porteer/src/weights.rs

Implemented according to: https://github.com/integritee-network/parachain/issues/312#issuecomment-2990491699
Almost finished WIP integrating it into the parachain for finetuning

Add pallet porteer

---

.github/workflows/ci.yml
rust-toolchain.toml

use wasm32-unknown-unknown again
